# Generated by Django 5.1.5 on 2025-02-06 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='like',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='friend',
        ),
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.CharField(choices=[('happy', '🥰'), ('sad', '😢'), ('angry', '😡'), ('funny', '🤣'), ('tired', '😪')], default='happy', max_length=10),
        ),
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sunny', '☀️'), ('cloudy', '☁️'), ('rainy', '🌧'), ('snowy', '❄️')], default='sunny', max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/%Y%m%d'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dog', '강아지'), ('cat', '고양이'), ('bird', '새'), ('rabbit', '토끼'), ('fish', '물고기'), ('hamster', '햄스터'), ('turtle', '거북이'), ('etc', '기타')], default='dog', max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', '남'), ('female', '여'), ('unknown', '없음')], default='male', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/%Y%m%d')),
                ('pet_fav', models.CharField(default='당근 간식을 가장 좋아해요', max_length=50)),
                ('pet_hate', models.CharField(default='낯선 사람을 정말 싫어해요', max_length=50)),
                ('pet_sig', models.CharField(default='눈이 정말 똘망똘망해요', max_length=50)),
                ('personal', models.ManyToManyField(blank=True, to='diaries.personality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='pet',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='diaries.pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diary',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaries.pet'),
        ),
        migrations.AddField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diaries.pet'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_kind', models.CharField(max_length=50)),
                ('plant_name', models.CharField(max_length=50)),
                ('plant_age', models.PositiveIntegerField()),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to='plant_images/%Y%m%d')),
                ('plant_con', models.CharField(max_length=50)),
                ('plant_sig', models.CharField(max_length=50)),
                ('plant_adv', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
