# Generated by Django 5.1.5 on 2025-01-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_images/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='friend_images/%Y%m%d'),
        ),
    ]
