# Generated by Django 5.1.5 on 2025-02-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_alter_diary_image_alter_friend_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.CharField(choices=[('male', '남'), ('female', '여'), ('unknown', '없음')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='friend',
            name='kind',
            field=models.CharField(choices=[('dog', '강아지'), ('cat', '고양이'), ('plant', '식물')], default='dog', max_length=10),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='personal',
        ),
        migrations.AddField(
            model_name='friend',
            name='personal',
            field=models.ManyToManyField(blank=True, to='diaries.personality'),
        ),
    ]
