# Generated by Django 5.1.5 on 2025-02-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_personality_remove_like_friend_remove_comment_friend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_kind',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='plant_name',
            new_name='name',
        ),
    ]
