# Generated by Django 5.1.5 on 2025-02-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_personality_alter_friend_gender_alter_friend_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sunny', '☀️'), ('cloudy', '☁️'), ('rainy', '🌧'), ('snowy', '❄️')], default='sunny', max_length=10),
        ),
    ]
