# Generated by Django 5.1.5 on 2025-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0003_rename_plant_age_plant_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
