# Generated by Django 5.1.5 on 2025-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_diary_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='mood',
            field=models.CharField(choices=[('happy', '🥰'), ('sad', '😢'), ('angry', '😡'), ('funny', '🤣'), ('tired', '😪')], default='happy', max_length=10),
        ),
    ]
