# Generated by Django 5.1.5 on 2025-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_alter_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_fav',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_hate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_sig',
            field=models.CharField(max_length=50),
        ),
    ]
