# Generated by Django 5.1.5 on 2025-02-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_alter_pet_pet_fav_alter_pet_pet_hate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaries.plant'),
        ),
    ]
