# Generated by Django 5.1.5 on 2025-02-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_alter_pet_pet_fav_alter_pet_pet_hate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='like',
            name='diary_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
