# Generated by Django 5.1.5 on 2025-02-05 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0005_diary_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaries.friend'),
        ),
    ]
