# Generated by Django 5.1.5 on 2025-02-04 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_alter_diary_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diaries.friend'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
