# Generated by Django 5.1.5 on 2025-02-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_diary_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='diary',
        ),
        migrations.RemoveField(
            model_name='like',
            name='diary_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='pet',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
