# Generated by Django 5.1.5 on 2025-02-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_diary_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='friend',
        ),
        migrations.AddField(
            model_name='friend',
            name='pet_fav',
            field=models.CharField(default='당근 간식을 가장 좋아해요', max_length=50),
        ),
        migrations.AddField(
            model_name='friend',
            name='pet_hate',
            field=models.CharField(default='낯선 사람을 정말 싫어해요', max_length=50),
        ),
        migrations.AddField(
            model_name='friend',
            name='pet_sig',
            field=models.CharField(default='눈이 정말 똘망똘망해요', max_length=50),
        ),
    ]
