# Generated by Django 5.1.5 on 2025-02-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_remove_diary_friend_friend_pet_fav_friend_pet_hate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_kind', models.CharField(max_length=50)),
                ('plant_name', models.CharField(max_length=50)),
                ('plant_age', models.PositiveIntegerField()),
                ('plant_image', models.ImageField(blank=True, null=True, upload_to='plant_images/%Y%m%d')),
                ('plant_con', models.CharField(default='요즘 이파리가 시들시들해요', max_length=50)),
                ('plant_sig', models.CharField(default='꽃 향기가 좋아요', max_length=50)),
                ('plant_adv', models.CharField(default='한결같이 우리집 베란다에 있는 모습습', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
