# Generated by Django 5.1.5 on 2025-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_remove_like_diary_remove_like_diary_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
