# Generated by Django 5.1.5 on 2025-02-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_diary_friend_alter_diary_date'),
        ('diaries', '0008_plant'),
    ]

    operations = [
    ]
