# Generated by Django 5.1.5 on 2025-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0009_alter_diary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mood',
            field=models.CharField(choices=[('happy', '🥰'), ('funny', '🤣'), ('excited', '🤩'), ('normal', '😌'), ('sad', '😢'), ('angry', '😡'), ('tired', '😪')], default='happy', max_length=10),
        ),
        migrations.AlterField(
            model_name='diary',
            name='weather',
            field=models.CharField(choices=[('sunny', '☀️'), ('windy', '💨'), ('cloudy', '☁️'), ('hot', '🔥'), ('cold', '🥶'), ('rainy', '🌧'), ('snowy', '❄️')], default='sunny', max_length=10),
        ),
    ]