# Generated by Django 5.1.5 on 2025-02-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0010_alter_plant_plant_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_adv',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_con',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_sig',
            field=models.CharField(max_length=50),
        ),
    ]
