# Generated by Django 5.1.5 on 2025-02-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0010_alter_plant_plant_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
