# Generated by Django 5.1.5 on 2025-02-10 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('diaries', '0007_remove_like_diary_remove_like_diary_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='diaries.diary'),
        ),
    ]
