# Generated by Django 5.1.5 on 2025-02-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_diary_friend_alter_diary_date'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='diaries.diary'),
        ),
    ]
