# Generated by Django 5.1.5 on 2025-02-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0007_remove_diary_friend_friend_pet_fav_friend_pet_hate_and_more'),
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='diaries.diary'),
        ),
    ]